# Header
menu:
  主页: /
# 归档: /archives
  目录: /categories
  标签: /tags
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 更多内容
fancybox: true

# Sidebar
sidebar: bottom
widgets:
#- category
#- tag
#- tagcloud
- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
authoricon: heart
twitter:
google_plus:
fb_admins:
fb_app_id:

duoshuo_shortname: tracy626
duoshuo_share: 1

# Social Links
weibo: http://weibo.com/5591067241/profile?topnav=1&wvr=6
bilibili: http://space.bilibili.com/1697667/